<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RimMult.Server</RootNamespace>
    <AssemblyName>RimMult.Server</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimMult.Net.LiteNet\RimMult.Net.LiteNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="server.example.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
